Updated CI-CD pipeline.yml
Checks Django Migration

diff --git a/.github/workflows/CI-CD pipeline.yml b/.github/workflows/CI-CD pipeline.yml
--- a/.github/workflows/CI-CD pipeline.yml
+++ b/.github/workflows/CI-CD pipeline.yml
@@ -1,30 +1,35 @@
-name: CI-CD pipeline
+name: Django Migration Check
 
-on:
-  push:
-    branches:
-      - main
+with: 
+  app-path: accounts
 
-jobs:
-  check-urls:
-    runs-on: ubuntu-latest
+# name: CI-CD pipeline
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+# on:
+#   push:
+#     branches:
+#       - main
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.11
+# jobs:
+#   check-urls:
+#     runs-on: ubuntu-latest
 
-      - name: Check urlpatterns in urls.py
-        run: |
-          file_path="Backend/accounts/urls.py"
-          if grep -qE 'urlpatterns = \[' $file_path; then
-            echo "urlpatterns found in $file_path"
-            exit 0  # Success
-          else
-            echo "No urlpatterns found in $file_path"
-            exit 1  # Failure
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       - name: Set up Python
+#         uses: actions/setup-python@v2
+#         with:
+#           python-version: 3.11
+
+#       - name: Check urlpatterns in urls.py
+#         run: |
+#           file_path="Backend/accounts/urls.py"
+#           if grep -qE 'urlpatterns = \[' $file_path; then
+#             echo "urlpatterns found in $file_path"
+#             exit 0  # Success
+#           else
+#             echo "No urlpatterns found in $file_path"
+#             exit 1  # Failure
 
